spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 354236654955-ivnba0pee9si02v8rnk0tac1mineh2lu.apps.googleusercontent.com
            client-secret: WKpwSHoR39Nl-x6ts51M8m_Q
            scope: profile,email
          naver:
            client-id: F3l6Yw5NnG9c0N2A0TPP
            client-secret: aefhsVVnPw
            redirect_uri_template: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization_grant_type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
